services:
  rgallery:
    image: robbymilo/rgallery:latest
    build:
      context: .
      dockerfile: cmd/rgallery/Dockerfile
    # entrypoint:
    #   - rgallery
    #   - --data=./data # override database directory
    #   - --cache=./cache # override cache directory
    #   - --quality=60 # override thumbnail quality
    #   - --location-dataset=Countries10 # use lower resolution reverse geocode dataset
    #   - --tile-server=https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=<replace-with-your-API-key>
    #   - --include-originals=true # include originals in web view.
    # platform: linux/arm64
    platform: linux/amd64
    environment:
      - RGALLERY_RESIZE_SERVICE=http://rgallery-resize:3001
      - RGALLERY_LOCATION_SERVICE=http://rgallery-geo:3002
    volumes:
      - ./media:/media:ro # path to your media files
      - ./data:/data # path to the rgallery database directory
      - ./cache:/cache # path to the rgallery cache directory
    ports:
      - 3000:3000

  rgallery-resize:
    image: robbymilo/rgallery:resize-latest
    build:
      context: .
      dockerfile: cmd/rgallery-resize/Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    # platform: linux/arm64
    platform: linux/amd64
    ports:
      - 3001

  rgallery-geo:
    image: robbymilo/rgallery:geo-latest
    build:
      context: .
      dockerfile: cmd/rgallery-geo/Dockerfile
    # platform: linux/arm64
    platform: linux/amd64
    ports:
      - 3002
