aliases:
  lenses: # exif:alias
    "70.0-200.0 mm f/f2.8": "AF-S Nikkor 70-200mm f/2.8G ED VR II"
    "VR 70-200mm f/2.8G": "AF-S Nikkor 70-200mm f/2.8G ED VR II"
    "AF-S Nikkor 70-200mm f/2.8G ED VR II": "AF-S Nikkor 70-200mm f/2.8G ED VR II"